### ISSUE TITLE
check error at m350g6a

### ISSUE THREAD

**Issue by himorin** [himorin/megacli2prom#1]
$ sudo /usr/local/src/github/himorin/megacli2prom/megacli.py 
Traceback (most recent call last):
  File "/usr/local/src/github/himorin/megacli2prom/megacli.py", line 309, in <module>
    main()
  File "/usr/local/src/github/himorin/megacli2prom/megacli.py", line 298, in main
    exec(a)
  File "<string>", line 1, in <module>
IndexError: list index out of range

**Comment by himorin** [comment]
fixed by 63cf212
